### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nathanclevenger** [graphdl/saas#1]
- [ ] Define SaaS Primitives
- [ ] Define API-based Product
- [ ] Define CRUD App-based Product
- [ ] Define Landing Page
- [ ] Define Directory Website
- [ ] Define Documentation Site
- [ ] Define SaaS apps needed by every SaaS
